from flask import Flask, render_template, request, jsonify
import ollama
import time

app = Flask(__name__)

# ============================================================
# MODELO A: responde (Llama 3.1 8B)
# ============================================================
def modelo_a_responde(pregunta, idioma):
    prompt_final = f"""
Responde en el idioma indicado: {idioma}

Pregunta:
{pregunta}
"""

    start_a = time.time()
    respuesta_a_raw = ollama.generate(
        model="llama3.1:8b",
        prompt=prompt_final
    )
    tiempo_a = time.time() - start_a

    return {
        "texto": respuesta_a_raw["response"],
        "tiempo": tiempo_a,
        "tokens": respuesta_a_raw.get("eval_count", 0),
        "prompt_tokens": respuesta_a_raw.get("prompt_eval_count", 0)
    }


# ============================================================
# MODELO B: evalúa (Qwen 0.6B) — MULTILINGÜE + MÉTRICAS + RAZONAMIENTO SEPARADO
# ============================================================
def modelo_b_evalua(respuesta_a_texto, idioma):

    prompts = {
        "es": f"""
Evalúa la siguiente respuesta generada por otro modelo.
Responde en español.

RESPUESTA DEL MODELO A:
{respuesta_a_texto}

Dame:

1. Si la explicación es correcta.
2. Si falta algo importante.
3. Si hay errores conceptuales.
4. Cómo mejorarla.

5. Un panel de calidad con:
   - claridad (0–10)
   - precisión (0–10)
   - profundidad (0–10)
   - relevancia (0–10)
   - score total (promedio)

6. Un detector de alucinaciones:
   - score (0–10)
   - explicación de qué parte parece inventada

Primero escribe toda la EVALUACIÓN.
Luego, en una sección separada titulada exactamente:
RAZONAMIENTO:
explica paso a paso:

- por qué dijiste que es correcta o no
- por qué detectaste errores
- por qué diste esas métricas
- cómo llegaste a tu juicio final
""",

        "en": f"""
Evaluate the following response generated by another model.
Respond in English.

RESPONSE FROM MODEL A:
{respuesta_a_texto}

Give me:

1. Whether the explanation is correct.
2. Whether something important is missing.
3. Whether there are conceptual errors.
4. How to improve it.

5. A quality panel with:
   - clarity (0–10)
   - accuracy (0–10)
   - depth (0–10)
   - relevance (0–10)
   - total score (average)

6. A hallucination detector:
   - score (0–10)
   - explanation of what seems invented

First write the full EVALUATION.
Then, in a separate section titled exactly:
RAZONAMIENTO:
explain step by step:

- why you said it is correct or not
- why you detected errors
- why you gave those metrics
- how you reached your final judgment
""",

        "sv": f"""
Utvärdera följande svar som genererats av en annan modell.
Svara på svenska.

SVAR FRÅN MODELL A:
{respuesta_a_texto}

Ge mig:

1. Om förklaringen är korrekt.
2. Om något viktigt saknas.
3. Om det finns konceptuella fel.
4. Hur man kan förbättra svaret.

5. En kvalitetsbedömning med:
   - tydlighet (0–10)
   - noggrannhet (0–10)
   - djup (0–10)
   - relevans (0–10)
   - totalpoäng (medelvärde)

6. En hallucinationsdetektor:
   - poäng (0–10)
   - förklaring av vad som verkar påhittat

Skriv först hela UTVÄRDERINGEN.
Sedan, i en separat sektion med rubriken:
RAZONAMIENTO:
förklarar du steg för steg:

- varför du sa att det är korrekt eller inte
- varför du hittade fel
- varför du gav dessa poäng
- hur du kom fram till din slutliga bedömning
"""
    }

    prompt_evaluacion = prompts[idioma]

    start_b = time.time()
    evaluacion_b_raw = ollama.generate(
        model="qwen3:0.6b",
        prompt=prompt_evaluacion
    )
    tiempo_b = time.time() - start_b

    texto_completo = evaluacion_b_raw["response"]

    # ============================
    # SEPARADOR ROBUSTO
    # ============================
    marcadores = [
        "RAZONAMIENTO:",
        "Razonamiento:",
        "RAZONING:",
        "Razoning:",
        "Razonamiento del modelo B:",
        "Razonamiento del Modelo B:"
    ]

    pos = -1
    marcador_usado = None

    for m in marcadores:
        if m in texto_completo:
            pos = texto_completo.index(m)
            marcador_usado = m
            break

    if pos != -1:
        evaluacion = texto_completo[:pos].strip()
        razonamiento = texto_completo[pos + len(marcador_usado):].strip()
    else:
        evaluacion = texto_completo.strip()
        razonamiento = ""

    return {
        "texto": evaluacion,
        "razonamiento": razonamiento,
        "tiempo": tiempo_b,
        "tokens": evaluacion_b_raw.get("eval_count", 0),
        "prompt_tokens": evaluacion_b_raw.get("prompt_eval_count", 0)
    }


# ============================================================
# MODELO C: refinador (Qwen 0.6B) — MINI RLHF COMPLETO
# ============================================================
def modelo_c_refina(respuesta_a, evaluacion_b, razonamiento_b, correccion_humana, idioma):
    prompt_refinar = f"""
Refina la respuesta original usando:

- La respuesta del Modelo A
- La evaluación del Modelo B
- El razonamiento del Modelo B
- La corrección humana
- El idioma seleccionado: {idioma}

RESPUESTA ORIGINAL:
{respuesta_a}

EVALUACIÓN DEL MODELO B:
{evaluacion_b}

RAZONAMIENTO DEL MODELO B:
{razonamiento_b}

CORRECCIÓN HUMANA:
{correccion_humana}

Genera una versión mejorada, más precisa, más clara, sin alucinaciones,
y completamente en el idioma indicado.
"""

    start_c = time.time()
    refinado_raw = ollama.generate(
        model="qwen3:0.6b",
        prompt=prompt_refinar
    )
    tiempo_c = time.time() - start_c

    return {
        "texto": refinado_raw["response"],
        "tiempo": tiempo_c,
        "tokens": refinado_raw.get("eval_count", 0),
        "prompt_tokens": refinado_raw.get("prompt_eval_count", 0)
    }


# -----------------------------
# RUTA DEL FRONT-END
# -----------------------------
@app.route("/duelo")
def duelo():
    return render_template("duelo.html")


# -----------------------------
# API: respuesta + evaluación
# -----------------------------
@app.route("/api/duelo", methods=["POST"])
def api_duelo():
    data = request.json
    pregunta = data["pregunta"]
    idioma = data["idioma"]

    modelo_a = modelo_a_responde(pregunta, idioma)
    modelo_b = modelo_b_evalua(modelo_a["texto"], idioma)

    return jsonify({
        "idioma": idioma,
        "respuesta_a": modelo_a["texto"],
        "evaluacion_b": modelo_b["texto"],
        "razonamiento_b": modelo_b["razonamiento"],
        "tiempo_a": modelo_a["tiempo"],
        "tiempo_b": modelo_b["tiempo"],
        "tokens_a": modelo_a["tokens"],
        "tokens_b": modelo_b["tokens"],
        "prompt_tokens_a": modelo_a["prompt_tokens"],
        "prompt_tokens_b": modelo_b["prompt_tokens"]
    })


# -----------------------------
# API: refinamiento RLHF
# -----------------------------
@app.route("/api/refinar", methods=["POST"])
def api_refinar():
    data = request.json

    respuesta_a = data["respuesta_a"]
    evaluacion_b = data["evaluacion_b"]
    razonamiento_b = data["razonamiento_b"]
    correccion_humana = data["correccion_humana"]
    idioma = data["idioma"]

    refinado = modelo_c_refina(respuesta_a, evaluacion_b, razonamiento_b, correccion_humana, idioma)

    return jsonify({
        "idioma": idioma,
        "refinado": refinado["texto"],
        "tiempo_c": refinado["tiempo"],
        "tokens_c": refinado["tokens"],
        "prompt_tokens_c": refinado["prompt_tokens"]
    })


# -----------------------------
# RUN
# -----------------------------
if __name__ == "__main__":
    app.run(debug=True)