from flask import Flask, render_template, request, jsonify
import ollama
import time

app = Flask(__name__)

# ============================================================
# MODELO A: responde (Llama 3.1 8B)
# ============================================================
def modelo_a_responde(pregunta, idioma):
    prompt_final = f"""
Responde en el idioma indicado: {idioma}

Pregunta:
{pregunta}
"""

    start_a = time.time()
    respuesta_a_raw = ollama.generate(
        model="llama3.1:8b",
        prompt=prompt_final
    )
    tiempo_a = time.time() - start_a

    return {
        "texto": respuesta_a_raw["response"],
        "tiempo": tiempo_a,
        "tokens": respuesta_a_raw.get("eval_count", 0),
        "prompt_tokens": respuesta_a_raw.get("prompt_eval_count", 0)
    }


# ============================================================
# MODELO B: evalúa (Qwen 0.6B) — MULTILINGÜE + MÉTRICAS + RAZONAMIENTO
# ============================================================
def modelo_b_evalua(respuesta_a_texto, idioma):

    prompts = {
        "es": f"""
Evalúa la siguiente respuesta generada por otro modelo.
Responde en español.

RESPUESTA DEL MODELO A:
{respuesta_a_texto}

Dame:

1. Si la explicación es correcta.
2. Si falta algo importante.
3. Si hay errores conceptuales.
4. Cómo mejorarla.

5. Un panel de calidad con:
   - claridad (0–10)
   - precisión (0–10)
   - profundidad (0–10)
   - relevancia (0–10)
   - score total (promedio)

6. Un detector de alucinaciones:
   - score (0–10)
   - explicación de qué parte parece inventada

7. Explica tu razonamiento paso a paso.
""",

        "en": f"""
Evaluate the following response generated by another model.
Respond in English.

RESPONSE FROM MODEL A:
{respuesta_a_texto}

Give me:

1. Whether the explanation is correct.
2. Whether something important is missing.
3. Whether there are conceptual errors.
4. How to improve it.

5. A quality panel with:
   - clarity (0–10)
   - accuracy (0–10)
   - depth (0–10)
   - relevance (0–10)
   - total score (average)

6. A hallucination detector:
   - score (0–10)
   - explanation of what seems invented

7. Explain your reasoning step by step.
""",

        "sv": f"""
Utvärdera följande svar som genererats av en annan modell.
Svara på svenska.

SVAR FRÅN MODELL A:
{respuesta_a_texto}

Ge mig:

1. Om förklaringen är korrekt.
2. Om något viktigt saknas.
3. Om det finns konceptuella fel.
4. Hur man kan förbättra svaret.

5. En kvalitetsbedömning med:
   - tydlighet (0–10)
   - noggrannhet (0–10)
   - djup (0–10)
   - relevans (0–10)
   - totalpoäng (medelvärde)

6. En hallucinationsdetektor:
   - poäng (0–10)
   - förklaring av vad som verkar påhittat

7. Förklara ditt resonemang steg för steg.
"""
    }

    prompt_evaluacion = prompts[idioma]

    start_b = time.time()
    evaluacion_b_raw = ollama.generate(
        model="qwen3:0.6b",
        prompt=prompt_evaluacion
    )
    tiempo_b = time.time() - start_b

    texto_completo = evaluacion_b_raw["response"]

    return {
        "texto": texto_completo,
        "tiempo": tiempo_b,
        "tokens": evaluacion_b_raw.get("eval_count", 0),
        "prompt_tokens": evaluacion_b_raw.get("prompt_eval_count", 0)
    }


# -----------------------------
# RUTA DEL FRONT-END
# -----------------------------
@app.route("/duelo")
def duelo():
    return render_template("duelo.html")


# -----------------------------
# API PARA EL FRONT-END
# -----------------------------
@app.route("/api/duelo", methods=["POST"])
def api_duelo():
    data = request.json
    pregunta = data["pregunta"]
    idioma = data["idioma"]  # viene del selector del frontend

    modelo_a = modelo_a_responde(pregunta, idioma)
    modelo_b = modelo_b_evalua(modelo_a["texto"], idioma)

    return jsonify({
        "idioma": idioma,
        "respuesta_a": modelo_a["texto"],
        "evaluacion_b": modelo_b["texto"],
        "tiempo_a": modelo_a["tiempo"],
        "tiempo_b": modelo_b["tiempo"],
        "tokens_a": modelo_a["tokens"],
        "tokens_b": modelo_b["tokens"],
        "prompt_tokens_a": modelo_a["prompt_tokens"],
        "prompt_tokens_b": modelo_b["prompt_tokens"]
    })


# -----------------------------
# RUN
# -----------------------------
if __name__ == "__main__":
    app.run(debug=True)